In [ ]:

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

# Original input files
BASE_DIR = "/content/drive/MyDrive/GSE149009"

clinical_path = os.path.join(
    BASE_DIR, "GSE149009_clean_clinical_metadata.csv"
)
expression_path = os.path.join(
    BASE_DIR, "GSE149009_gbm_rna_deseq2.txt"
)

# Check that both files exist
for path in [clinical_path, expression_path]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")
    print("Found:", path)

# Load the files
clinical = pd.read_csv(clinical_path)
expression = pd.read_csv(
    expression_path, sep="\t", index_col=0
)

print("Clinical metadata shape:", clinical.shape)
print("Expression matrix shape:", expression.shape)

display(clinical.head())
display(expression.iloc[:5, :5])

Mounted at /content/drive
Found: /content/drive/MyDrive/GSE149009/GSE149009_clean_clinical_metadata.csv
Found: /content/drive/MyDrive/GSE149009/GSE149009_gbm_rna_deseq2.txt
Clinical metadata shape: (68, 12)
Expression matrix shape: (37361, 68)

,patient_id,gsm_as_listed_in_dictionary,disease_state,age,gender,idh_mutation,survival_days,tissue,gsm,gsm_mapping_note,expr_column,survival_missing
0,G1,GSM4487293,GBM (IV),53.0,M,WT,22.0,GBM tumor tissue,GSM4487293,GEO Series roster sequence; OtB mapping cross-...,OtB6179,False
1,G2,GSM4487294,GBM (IV),69.0,M,NaN,25.0,GBM tumor tissue,GSM4487294,GEO Series roster sequence; OtB mapping cross-...,OtB6180,False
2,G3,GSM4487295,GBM (IV),36.0,M,WT,31.0,GBM tumor tissue,GSM4487295,GEO Series roster sequence; OtB mapping cross-...,OtB6181,False
3,G4,GSM4487296,GBM (IV),68.0,M,NaN,32.0,GBM tumor tissue,GSM4487296,GEO Series roster sequence; OtB mapping cross-...,OtB6182,False
4,G5,GSM4487297,GBM (IV),74.0,F,NaN,185.0,GBM tumor tissue,GSM4487297,GEO Series roster sequence; OtB mapping cross-...,OtB6183,False

                  OtB6179   OtB6180   OtB6181   OtB6182    OtB6183
ENSG
ENSG00000000003  5.828821  6.240547  6.959024  6.716199   7.711898
ENSG00000000005  3.602619  3.602619  3.602619  3.602619   3.602619
ENSG00000000419  4.687706  5.080394  5.480945  5.279210   3.602619
ENSG00000000457  6.172641  5.581485  6.391304  5.642001   8.708584
ENSG00000000460  6.013425  5.606976  7.124049  4.997947  10.533999

In [ ]:
from google.colab import drive
# ============================================================
# GBM SURVIVAL + GO PATHWAY ANALYSIS: FULL RECOVERY SCRIPT
# Dataset: GSE149009
#
# Rebuilds gene-survival correlations from the original files,
# corrects p-values for multiple testing, annotates Ensembl IDs,
# creates a unique-symbol preranked gene list, and runs GSEA.
#
# IMPORTANT:
# - This is an exploratory association analysis.
# - Survival days may be censored; Spearman correlation does not
#   replace a censoring-aware survival model.
# - GSEA results can differ from the earlier analysis because
#   duplicate gene symbols are resolved differently here.
# ============================================================

# ----------------------------
# 1. MOUNT GOOGLE DRIVE
# ----------------------------

from google.colab import drive
drive.mount('/content/drive')

# ----------------------------
# 2. INSTALL REQUIRED PACKAGES
# ----------------------------

!pip -q install mygene gseapy statsmodels scipy pandas numpy

# ----------------------------
# 3. IMPORT LIBRARIES
# ----------------------------

import os
import time
import warnings
import numpy as np
import pandas as pd
import mygene
import gseapy as gp

from scipy.stats import spearmanr
from statsmodels.stats.multitest import multipletests

warnings.filterwarnings("ignore", category=RuntimeWarning)

# ----------------------------
# 4. DEFINE FILE LOCATIONS
# ----------------------------

DATA_DIR = '/content/drive/MyDrive/GSE149009'
OUT_DIR = os.path.join(DATA_DIR, 'recovered_full_analysis')

os.makedirs(OUT_DIR, exist_ok=True)

CLINICAL_FILE = os.path.join(
    DATA_DIR, 'GSE149009_clean_clinical_metadata.csv'
)

EXPRESSION_FILE = os.path.join(
    DATA_DIR, 'GSE149009_gbm_rna_deseq2.txt'
)

# Verify both source files exist before continuing.
for path in [CLINICAL_FILE, EXPRESSION_FILE]:
    if not os.path.exists(path):
        raise FileNotFoundError(
            f'File not found: {path}\n'
            'Check the filename and Google Drive folder.'
        )

print('Source files found:')
print(CLINICAL_FILE)
print(EXPRESSION_FILE)
print()

# ----------------------------
# 5. LOAD AND VALIDATE DATA
# ----------------------------

clinical = pd.read_csv(CLINICAL_FILE)

expression = pd.read_csv(
    EXPRESSION_FILE,
    sep='\t',
    index_col=0
)

print('Clinical metadata shape:', clinical.shape)
print('Expression matrix shape:', expression.shape)

required_columns = ['survival_days', 'expr_column']

missing_columns = [
    c for c in required_columns if c not in clinical.columns
]

if missing_columns:
    raise ValueError(
        f'Missing clinical columns: {missing_columns}'
    )

# Remove samples without survival information.
clinical_survival = clinical.dropna(
    subset=['survival_days']
).copy()

# Ensure the expression matrix contains the required samples.
samples = clinical_survival['expr_column'].astype(str).tolist()

missing_samples = [
    s for s in samples if s not in expression.columns
]

if missing_samples:
    raise ValueError(
        f'{len(missing_samples)} clinical samples were not found '
        f'in the expression matrix. Examples: {missing_samples[:10]}'
    )

# Convert expression and survival values to numeric.
X = expression.loc[:, samples].apply(
    pd.to_numeric, errors='coerce'
)

survival = pd.to_numeric(
    clinical_survival['survival_days'],
    errors='coerce'
).to_numpy(dtype=float)

# Check for missing/non-finite values.
if not np.isfinite(survival).all():
    raise ValueError(
        'Non-finite survival values remain after filtering.'
    )

if X.isna().any().any():
    raise ValueError(
        'Expression data contain missing or non-numeric values. '
        'Inspect the source matrix before continuing.'
    )

if len(samples) != 59:
    print(
        'WARNING: Expected 59 samples based on the previous run, '
        f'but found {len(samples)}.'
    )

print('Samples with survival data:', len(samples))
print('Genes in original matrix:', X.shape[0])
print('Survival days: median =',
      float(np.median(survival)),
      '| mean =', round(float(np.mean(survival)), 2))
print()

# Save a reproducibility summary.
audit = {
    'dataset': ['GSE149009'],
    'clinical_records': [len(clinical)],
    'expression_genes': [expression.shape[0]],
    'expression_samples': [expression.shape[1]],
    'samples_with_survival': [len(samples)],
    'mean_survival_days': [float(np.mean(survival))],
    'median_survival_days': [float(np.median(survival))]
}

pd.DataFrame(audit).to_csv(
    os.path.join(OUT_DIR, '00_audit_summary.csv'),
    index=False
)

# ----------------------------
# 6. SPEARMAN CORRELATION
#    FOR EACH NON-CONSTANT GENE
# ----------------------------

print('Calculating gene-survival correlations...')
print('This step may take a few minutes.')

rows = []
constant_genes = 0
invalid_genes = 0

for i, (gene, values) in enumerate(X.iterrows(), start=1):

    values = values.to_numpy(dtype=float)

    # Skip genes with no variation.
    if np.std(values) < 1e-10:
        constant_genes += 1
        continue

    rho, p_value = spearmanr(values, survival)

    if np.isfinite(rho) and np.isfinite(p_value):
        rows.append((str(gene), float(rho), float(p_value)))
    else:
        invalid_genes += 1

    if i % 5000 == 0:
        print(f'Processed {i:,} / {X.shape[0]:,} genes')

results = pd.DataFrame(
    rows,
    columns=['gene', 'spearman_rho', 'p_value']
)

if results.empty:
    raise RuntimeError(
        'No valid gene correlations were calculated.'
    )

# Benjamini-Hochberg FDR correction.
results['FDR'] = multipletests(
    results['p_value'].to_numpy(),
    method='fdr_bh'
)[1]

results = results.sort_values(
    'p_value'
).reset_index(drop=True)

results.to_csv(
    os.path.join(
        OUT_DIR,
        '01_full_gene_survival_associations.csv'
    ),
    index=False
)

# Full Ensembl-ID ranking, sorted by signed Spearman rho.
all_id_ranking = results[
    ['gene', 'spearman_rho']
].sort_values(
    'spearman_rho',
    ascending=False
)

all_id_ranking.to_csv(
    os.path.join(
        OUT_DIR,
        '02_prerank_all_Ensembl_IDs.csv'
    ),
    index=False
)

print()
print('GENE-LEVEL RESULTS')
print('------------------')
print('Genes tested:', len(results))
print('Constant genes removed:', constant_genes)
print('Invalid correlations skipped:', invalid_genes)
print('Genes with FDR < 0.05:',
      int((results['FDR'] < 0.05).sum()))
print()

# ----------------------------
# 7. ANNOTATE ENSEMBL IDS
#    USING MYGENE
# ----------------------------

print('Annotating gene IDs with MyGene.info...')

mg = mygene.MyGeneInfo()

gene_ids = results['gene'].astype(str).tolist()

# Remove version suffixes only for the annotation query.
# Preserve original IDs in the results table.
query_ids = [
    gene_id.split('.')[0] for gene_id in gene_ids
]

annotation_records = []

# Batch queries to improve reliability and allow retries.
BATCH_SIZE = 1000

for start in range(0, len(query_ids), BATCH_SIZE):

    batch = query_ids[start:start + BATCH_SIZE]

    for attempt in range(3):
        try:
            batch_results = mg.querymany(
                batch,
                scopes='ensembl.gene',
                fields='symbol,name',
                species='human',
                as_dataframe=False,
                returnall=False,
                verbose=False,
                dotfield=False
            )

            if isinstance(batch_results, dict):
                batch_results = batch_results.get(
                    'out', []
                )

            annotation_records.extend(batch_results)
            break

        except Exception as e:
            print(
                f'Annotation batch {start // BATCH_SIZE + 1} '
                f'failed (attempt {attempt + 1}/3): {e}'
            )

            if attempt == 2:
                raise RuntimeError(
                    'Gene annotation failed after 3 attempts. '
                    'Check the internet connection and rerun '
                    'this section.'
                )

            time.sleep(3 * (attempt + 1))

    completed = min(start + BATCH_SIZE, len(query_ids))
    print(f'Annotated-query progress: {completed:,} / {len(query_ids):,}')

ann_df = pd.DataFrame(annotation_records)

if ann_df.empty or 'query' not in ann_df.columns:
    raise RuntimeError(
        'MyGene returned no usable annotations. '
        'Check the service and try again.'
    )

# Keep only fields that actually exist in the response.
annotation_columns = ['query']

for col in ['symbol', 'name', 'notfound']:
    if col in ann_df.columns:
        annotation_columns.append(col)

ann_df = ann_df[annotation_columns].copy()

# Some IDs can produce multiple records. Retain one record per query.
ann_df = ann_df.drop_duplicates(
    subset=['query'],
    keep='first'
)

# Match results using version-stripped Ensembl IDs.
results_for_annotation = results.copy()
results_for_annotation['annotation_query'] = (
    results_for_annotation['gene']
    .astype(str)
    .str.split('.')
    .str[0]
)

annotated = results_for_annotation.merge(
    ann_df,
    left_on='annotation_query',
    right_on='query',
    how='left'
)

annotated = annotated.drop(
    columns=['query', 'annotation_query'],
    errors='ignore'
)

annotated.to_csv(
    os.path.join(
        OUT_DIR,
        '03_annotated_gene_survival_associations.csv'
    ),
    index=False
)

mapped_count = int(
    annotated['symbol'].notna().sum()
) if 'symbol' in annotated.columns else 0

print()
print('ANNOTATION RESULTS')
print('------------------')
print('IDs with symbols:', mapped_count)
print('IDs without symbols:', len(annotated) - mapped_count)
print()

if mapped_count == 0:
    raise RuntimeError(
        'No gene symbols were returned. Do not run GSEA '
        'until annotation has been fixed.'
    )

# ----------------------------
# 8. CREATE UNIQUE-SYMBOL
#    PRERANKED GENE LIST
# ----------------------------

print('Creating unique-symbol ranking...')

with_symbols = annotated.dropna(
    subset=['symbol']
).copy()

# Remove blank symbols.
with_symbols['symbol'] = (
    with_symbols['symbol'].astype(str).str.strip()
)

with_symbols = with_symbols[
    (with_symbols['symbol'] != '') &
    (with_symbols['symbol'].str.lower() != 'nan')
].copy()

with_symbols['abs_rho'] = (
    with_symbols['spearman_rho'].abs()
)

# Resolve duplicate symbols by retaining the gene with the
# strongest absolute correlation; use p-value to break ties.
unique_symbols = (
    with_symbols.sort_values(
        ['abs_rho', 'p_value'],
        ascending=[False, True]
    )
    .drop_duplicates(
        subset=['symbol'],
        keep='first'
    )
    .copy()
)

ranked = unique_symbols[
    ['symbol', 'spearman_rho', 'p_value', 'FDR']
].sort_values(
    'spearman_rho',
    ascending=False
)

ranked.to_csv(
    os.path.join(
        OUT_DIR,
        '04_prerank_unique_symbols.csv'
    ),
    index=False
)

print('Unique symbols supplied to GSEA:', len(ranked))
print()

if len(ranked) < 100:
    raise RuntimeError(
        'Unexpectedly few unique symbols were mapped. '
        'Inspect the annotation output before continuing.'
    )

# ----------------------------
# 9. RUN GO BIOLOGICAL PROCESS
#    PRERANKED GSEA
# ----------------------------

print('Running GO Biological Process preranked GSEA...')
print('Using 1,000 permutations and seed 42.')
print('This can take several minutes.')

gsea = gp.prerank(
    rnk=ranked[['symbol', 'spearman_rho']],
    gene_sets='GO_Biological_Process_2023',
    permutation_num=1000,
    min_size=15,
    max_size=500,
    seed=42,
    outdir=None,
    verbose=True
)

pathways = gsea.res2d.copy()

if pathways.empty:
    raise RuntimeError(
        'GSEA returned no pathways. Inspect the GSEA log '
        'and gene-set overlap.'
    )

pathways.to_csv(
    os.path.join(
        OUT_DIR,
        '05_GO_Biological_Process_prerank_REBUILT.csv'
    ),
    index=False
)

# Standardize FDR column to numeric.
fdr_column = 'FDR q-val'

if fdr_column not in pathways.columns:
    raise RuntimeError(
        f'Expected column {fdr_column!r} was not found. '
        f'Available columns: {list(pathways.columns)}'
    )

pathways[fdr_column] = pd.to_numeric(
    pathways[fdr_column],
    errors='coerce'
)

sig = pathways[
    pathways[fdr_column] < 0.05
].copy().sort_values(
    fdr_column,
    ascending=True
)

sig.to_csv(
    os.path.join(
        OUT_DIR,
        '06_significant_GO_pathways_FDR05.csv'
    ),
    index=False
)

# ----------------------------
# 10. PRINT TOP PATHWAYS
# ----------------------------

print()
print('=' * 65)
print('FINAL ANALYSIS SUMMARY')
print('=' * 65)

print('Samples included:', len(samples))
print('Genes tested:', len(results))
print('Constant genes removed:', constant_genes)
print('Genes with FDR < 0.05:',
      int((results['FDR'] < 0.05).sum()))
print('IDs with symbols:', mapped_count)
print('Unique symbols ranked:', len(ranked))
print('GO pathways tested:', len(pathways))
print('GO pathways with FDR < 0.05:', len(sig))
print()

if len(sig) > 0:
    print('TOP SIGNIFICANT GO PATHWAYS')
    print('---------------------------')

    display_columns = [
        c for c in [
            'Term',
            'NES',
            'NOM p-val',
            'FDR q-val',
            'FWER p-val'
        ] if c in sig.columns
    ]

    print(sig[display_columns].head(20).to_string(index=False))

else:
    print(
        'No GO pathways met the FDR < 0.05 threshold '
        'in this run.'
    )

# ----------------------------
# 11. SAVE A RUN SUMMARY
# ----------------------------

summary = pd.DataFrame([{
    'dataset': 'GSE149009',
    'survival_samples': len(samples),
    'original_expression_genes': X.shape[0],
    'genes_tested': len(results),
    'constant_genes_removed': constant_genes,
    'invalid_correlations_skipped': invalid_genes,
    'genes_FDR_below_005': int(
        (results['FDR'] < 0.05).sum()
    ),
    'IDs_with_symbols': mapped_count,
    'unique_symbols_ranked': len(ranked),
    'GO_pathways_tested': len(pathways),
    'GO_pathways_FDR_below_005': len(sig),
    'gene_sets': 'GO_Biological_Process_2023',
    'permutations': 1000,
    'seed': 42
}])

summary.to_csv(
    os.path.join(OUT_DIR, '07_final_run_summary.csv'),
    index=False
)

print()
print('ALL DONE.')
print('Output folder:')
print(OUT_DIR)
print()
print('FILES CREATED:')
for filename in sorted(os.listdir(OUT_DIR)):
    print(' -', filename)

print()
print(
    'Interpretation reminder: positive NES indicates enrichment '
    'toward genes positively correlated with observed survival; '
    'negative NES indicates enrichment toward genes negatively '
    'correlated with observed survival. These are associations, '
    'not evidence of causation.'
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 689.7/689.7 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB 3.4 MB/s eta 0:00:00
Source files found:
/content/drive/MyDrive/GSE149009/GSE149009_clean_clinical_metadata.csv
/content/drive/MyDrive/GSE149009/GSE149009_gbm_rna_deseq2.txt

Clinical metadata shape: (68, 12)
Expression matrix shape: (37361, 68)
Samples with survival data: 59
Genes in original matrix: 37361
Survival days: median = 171.0 | mean = 875.49

Calculating gene-survival correlations...
This step may take a few minutes.
Processed 5,000 / 37,361 genes
Processed 10,000 / 37,361 genes
Processed 15,000 / 37,361 genes
Processed 20,000 / 37,361 genes
Processed 25,000 / 37,361 genes
Processed 30,000 / 37,361 genes

GENE-LEVEL RESULTS
------------------
Genes tested: 30617
Constant genes removed: 6744
Invalid correlations skipped: 0
Genes with FDR < 0.05: 0

Annotating gene IDs with MyGene.info...
Annotated-query progress: 1,000 / 30,617
Annotated-query progress: 2,000 / 30,617
Annotated-query progress: 3,000 / 30,617
Annotated-query progress: 4,000 / 30,617
Annotated-query progress: 5,000 / 30,617
Annotated-query progress: 6,000 / 30,617
Annotated-query progress: 7,000 / 30,617
Annotated-query progress: 8,000 / 30,617
Annotated-query progress: 9,000 / 30,617
Annotated-query progress: 10,000 / 30,617
Annotated-query progress: 11,000 / 30,617
Annotated-query progress: 12,000 / 30,617
Annotated-query progress: 13,000 / 30,617
Annotated-query progress: 14,000 / 30,617
Annotated-query progress: 15,000 / 30,617
Annotated-query progress: 16,000 / 30,617
Annotated-query progress: 17,000 / 30,617
Annotated-query progress: 18,000 / 30,617
Annotated-query progress: 19,000 / 30,617
Annotated-query progress: 20,000 / 30,617
Annotated-query progress: 21,000 / 30,617
Annotated-query progress: 22,000 / 30,617
Annotated-query progress: 23,000 / 30,617
Annotated-query progress: 24,000 / 30,617
Annotated-query progress: 25,000 / 30,617
Annotated-query progress: 26,000 / 30,617
Annotated-query progress: 27,000 / 30,617
Annotated-query progress: 28,000 / 30,617
Annotated-query progress: 29,000 / 30,617
Annotated-query progress: 30,000 / 30,617
Annotated-query progress: 30,617 / 30,617

ANNOTATION RESULTS
------------------
IDs with symbols: 27928
IDs without symbols: 2689

Creating unique-symbol ranking...

2026-10-13 08:22:12,352 [WARNING] Duplicated values found in preranked stats: 20.70% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-10-13 08:22:12,353 [INFO] Parsing data files for GSEA.............................

Unique symbols supplied to GSEA: 26709

Running GO Biological Process preranked GSEA...
Using 1,000 permutations and seed 42.
This can take several minutes.

2026-10-13 08:22:12,561 [INFO] Downloading and generating Enrichr library gene sets......
2026-10-13 08:22:12,775 [INFO] 2697 gene_sets have been filtered out when max_size=500 and min_size=15
2026-10-13 08:22:12,777 [INFO] 2710 gene_sets used for further statistical testing.....
2026-10-13 08:22:12,780 [INFO] Start to run GSEA...Might take a while..................
2026-10-13 08:29:48,505 [INFO] Congratulations. GSEApy runs successfully................

=================================================================
FINAL ANALYSIS SUMMARY
=================================================================
Samples included: 59
Genes tested: 30617
Constant genes removed: 6744
Genes with FDR < 0.05: 0
IDs with symbols: 27928
Unique symbols ranked: 26709
GO pathways tested: 2710
GO pathways with FDR < 0.05: 66

TOP SIGNIFICANT GO PATHWAYS
---------------------------
                                                                                             Term      NES  NOM p-val  FDR q-val  FWER p-val
                                                           Mitochondrial Translation (GO:0032543) 2.349539   0.000000   0.000000       0.000
                                                       Mitochondrial Gene Expression (GO:0140053) 2.295154   0.000000   0.000449       0.001
                                                                Chromatin Remodeling (GO:0006338) 2.160135   0.000000   0.004787       0.015
                                                      mRNA Splicing, Via Spliceosome (GO:0000398) 2.115475   0.000000   0.006283       0.032
                                                              Chromatin Organization (GO:0006325) 2.087810   0.000000   0.006540       0.046
                                          Monoubiquitinated Protein Deubiquitination (GO:0035520) 2.071687   0.000000   0.006682       0.059
                         Regulation Of Transcription Elongation By RNA Polymerase II (GO:0034243) 2.074812   0.000000   0.007181       0.056
                      Positive Regulation Of DNA-templated Transcription, Elongation (GO:0032786) 2.096123   0.000000   0.007181       0.043
                                                                     mRNA Processing (GO:0006397) 2.054994   0.000000   0.007589       0.080
RNA Splicing, Via Transesterification Reactions With Bulged Adenosine As Nucleophile (GO:0000377) 2.118343   0.000000   0.007630       0.031
                Positive Regulation Of Transcription Elongation By RNA Polymerase II (GO:0032968) 2.055879   0.000000   0.008348       0.080
                                                                     Response To BMP (GO:0071772) 2.033397   0.000000   0.009183       0.117
               Cell Surface Receptor Signaling Pathway Involved In Heart Development (GO:0061311) 2.033896   0.001692   0.009948       0.117
                                                 Regulation Of DNA Metabolic Process (GO:0051052) 2.003141   0.000000   0.013720       0.178
                              Transcription Initiation At RNA Polymerase II Promoter (GO:0006367) 1.984701   0.000000   0.017473       0.236
                                                      Cellular Response To Radiation (GO:0071478) 1.977334   0.000000   0.018008       0.255
                                                     Endocardial Cushion Development (GO:0003197) 1.972847   0.000000   0.018057       0.272
                                                          Double-Strand Break Repair (GO:0006302) 1.927841   0.000000   0.023824       0.444
                                                             Nucleosome Organization (GO:0034728) 1.930671   0.000000   0.023884       0.431
                                        Transcription Preinitiation Complex Assembly (GO:0070897) 1.936745   0.000000   0.024107       0.405

ALL DONE.
Output folder:
/content/drive/MyDrive/GSE149009/recovered_full_analysis

FILES CREATED:
 - 00_audit_summary.csv
 - 01_full_gene_survival_associations.csv
 - 02_prerank_all_Ensembl_IDs.csv
 - 03_annotated_gene_survival_associations.csv
 - 04_prerank_unique_symbols.csv
 - 05_GO_Biological_Process_prerank_REBUILT.csv
 - 06_significant_GO_pathways_FDR05.csv
 - 07_final_run_summary.csv

Interpretation reminder: positive NES indicates enrichment toward genes positively correlated with observed survival; negative NES indicates enrichment toward genes negatively correlated with observed survival. These are associations, not evidence of causation.

In [ ]:
import os
import zipfile
from google.colab import files

folder = '/content/drive/MyDrive/GSE149009/recovered_full_analysis'
zip_path = '/content/GBM_GO_results.zip'

filenames = [
    '05_GO_Biological_Process_prerank_REBUILT.csv',
    '06_significant_GO_pathways_FDR05.csv'
]

with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as z:
    for filename in filenames:
        path = os.path.join(folder, filename)
        if not os.path.exists(path):
            raise FileNotFoundError(f'Cannot find: {path}')
        z.write(path, arcname=filename)

files.download(zip_path)

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/GSE149009/recovered_full_analysis/06_significant_GO_pathways_FDR05.csv'

df = pd.read_csv(path)
print(df.to_string(index=False))

   Name                                                                                              Term        ES       NES  NOM p-val  FDR q-val  FWER p-val   Tag % Gene %                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Lead_genes
prerank                                                            Mitochondrial Translation (GO:0032543)  0.555462  2.349539   0.000000   0.000000       0.000   59/98 29.22%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GATB;MRPL57;GATC;MRPL19;MRPL16;MRPS6;MRPS21;MRPL43;DROSHA;MRPL50;MRPS14;MRPL39;MRPL24;GADD45GIP1;MTG1;CHCHD1;MRPS31;MRPL10;MRPS28;QRSL1;MRPL18;MRPL45;MRPS15;MRPL53;MTIF3;MRPS10;MRPL13;MRPL3;MRPL11;MRPL51;MRPL28;MRPL21;MRPL22;MRPL42;MRPS26;MRPS23;MRPL33;IARS2;MRPL48;TSFM;MRPS5;FASTKD2;MRPS30;HARS1;MRPL36;MTIF2;MRPL4;LARS2;MRPL1;MRPL14;MRPL44;MRPL12;MRPS22;MRPL34;MRPS33;MRPL55;MRPL9;NDUFA7;MRPL37
prerank                                                        Mitochondrial Gene Expression (GO:0140053)  0.539610  2.295154   0.000000   0.000449       0.001  64/102 30.40%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 GATB;MRPL57;GATC;MRPL19;MRPL16;MRPS6;MRPS21;MRPL43;MRPL50;MRPS14;MRPL39;MRPL24;GADD45GIP1;MTG1;CHCHD1;MRPS31;MRPL10;MRPS28;QRSL1;MRPL18;MRPL45;MRPS15;MRPL53;MRPS10;MRPL13;MRPL3;TWNK;MRPL11;MTERF3;MRPL51;MRPL28;MRPL21;MRPL22;MRPL42;MRPS26;MRPS23;MRPL33;IARS2;TFAM;MRPL48;MRPS5;FASTKD2;TEFM;MRPS30;HARS1;MRPL36;MRPL4;LARS2;MRPL1;MRPL14;MRPL44;FASTKD3;MRPL12;FASTKD5;MRPS22;MRPL34;MRPS33;MRPL55;MRPL9;NDUFA7;MRPL37;FASTKD1;MRPL27;FOXO3
prerank                                                                 Chromatin Remodeling (GO:0006338)  0.456525  2.160135   0.000000   0.004787       0.015 124/227 31.12%                                                                                                                                                                                                                                                                                                                         MCM3AP;APLF;DPF2;TADA2B;DAXX;MIER1;CTCF;PWWP2B;HIRA;CFDP1;WAC;PHF1;YY1;CHD3;SMARCC2;PRIMPOL;NPM1;DDX21;DEPDC1B;RNF168;MYC;SETD4;BPTF;BRD7;SFPQ;SMARCA4;HPF1;TOP1;KAT2A;ZBTB1;BAZ1A;TET1;CHTOP;ASF1A;HDGFL2;HCFC1;HDGFL3;NPM3;CECR2;SIRT7;HDGF;CHRAC1;SMARCC1;ZNF335;GATAD2B;KDM4E;PHF10;RNF2;BICRAL;PCGF2;BRDT;RBBP7;HDAC4;SUV39H2;KDM5B;PARP2;PSIP1;SKP1;GET1;MYBBP1A;TTI1;SF3B1;UBR5;PCGF1;JARID2;KDM5D;PHC1;CHD8;GLMN;INO80B;MBD3;BAZ2A;BMI1;FOXP3;SETDB1;RNF8;ERCC6;PIH1D1;HDAC6;INO80D;BCL7A;PAXIP1;ACTL6B;HNRNPC;BRD9;BABAM1;CHEK1;ATRX;CBX3;ACTR5;SUPT6H;PHB1;MTA2;RING1;SETDB2;USP3;SMARCD2;CHD7;MTF2;ACTL6A;CGGBP1;IWS1;NFAT5;SMARCB1;H3C1;CHD6;KDM5A;SMARCA1;KDM4B;INO80C;PER2;ARID2;GATAD2A;DEK;BAZ1B;KAT5;YEATS2;HP1BP3;LIN54;EZH1;SMARCAD1;BAZ2B;MTA3;HDAC2
prerank                                                       mRNA Splicing, Via Spliceosome (GO:0000398)  0.451286  2.115475   0.000000   0.006283       0.032 108/209 32.47%                                                                                                                                                                                                                                                                                                                                                                                                        RBMX2;USP49;RBM17;HNRNPH3;SNRNP70;IK;RBM41;HTATSF1;PPWD1;COIL;DDX39B;DHX16;GPKOW;PNN;HNRNPA1;BUD13;SFPQ;PABPC1;RSRC1;SNRNP35;DDX46;NCBP2L;CDC5L;DBR1;CWC27;LSM6;PPIE;SNRPB2;WBP4;SNRNP27;FRA10AC1;SRSF8;PQBP1;GEMIN4;TGS1;LSM2;PPIH;GEMIN7;SRSF1;SMN1;DDX41;HNRNPU;CTNNBL1;AQR;SF3B1;DDX1;GEMIN5;PRPF31;WDR83;SNRPE;ESS2;U2AF1;SDE2;CLNS1A;SRSF4;ZMAT2;CRNKL1;RBMXL2;MTREX;PLRG1;DHX38;TXNL4A;DCPS;SNRPD3;HNRNPC;SNRPG;DHX15;NCBP2;PRPF40B;RBM4;SYF2;HNRNPK;SRSF3;LSM3;LSM7;TRA2A;RBM8A;SF3B2;FRG1;SART1;RNPC3;SF3B3;CWC22;SNRPF;GPATCH1;SRSF9;PRPF19;HNRNPH1;RBM4B;DHX35;HNRNPR;PRPF3;PPIL1;SRSF12;RBM10;PRPF40A;DHX9;SF3A3;MFAP1;SRRM2;SCNM1;HSPA8;SNRPB;SNIP1;CDK13;GEMIN6;ISY1;SNRPD1
prerank                                                               Chromatin Organization (GO:0006325)  0.434427  2.087810   0.000000   0.006540       0.046 116/267 24.65%                                                                                                                                                                                                                                                                                                                                                                               H3-4;DPF2;TADA2B;DAXX;MIER1;CTCF;PWWP2B;SIRT1;KAT6B;HIRA;CFDP1;ING5;WAC;PHF1;YY1;CBX5;CHD3;SMARCC2;ING4;NPM1;L3MBTL1;DDX21;GRWD1;BRD2;MYC;SETD4;BPTF;BRD7;NAP1L1;BANF1;SSRP1;DNAJC9;SFPQ;SMARCA4;TOP1;KAT2A;ZBTB1;BAZ1A;SOX15;TET1;CHTOP;ASF1A;HDGFL2;HCFC1;HDGFL3;ANP32B;H3-3A;NPM3;CECR2;HDGF;SUPT16H;CHRAC1;SMARCC1;GATAD2B;KDM4E;DDX11;PHF10;RNF2;BICRAL;PCGF2;BRDT;RBBP7;HDAC4;SUV39H2;H2BC14;KDM5B;HDAC3;PSIP1;HNRNPU;SKP1;GET1;MYBBP1A;H2BC3;TTI1;SF3B1;PCGF1;JARID2;KDM5D;PHC1;CHD8;INO80B;MBD3;BAZ2A;BMI1;FOXP3;ERCC6;PIH1D1;INO80D;HAT1;SOX2;BCL7A;PAXIP1;ACTL6B;HNRNPC;BRD9;PWWP3A;CHEK1;NAP1L3;ATRX;CBX3;CHAF1B;ACTR5;HDAC10;MTA2;RING1;CBX1;MOS;H2BC8;UBN1;SMARCD2;CHD7;MTF2;ACTL6A;IWS1;SMARCB1;H3C1
prerank                                           Monoubiquitinated Protein Deubiquitination (GO:0035520)  0.605217  2.071687   0.000000   0.006682       0.059   17/33 16.55%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ENY2;TADA2B;SUPT3H;TAF5L;SUPT7L;KAT2A;TAF5;TAF4;USP7;TMEM98;USP47;RNF2;SUPT20H;USP9X;USP1;USP16;TAF7
prerank                          Regulation Of Transcription Elongation By RNA Polymerase II (GO:0034243)  0.507792  2.074812   0.000000   0.007181       0.056   40/77 28.20%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MED16;MED20;PWWP2B;MED30;INTS2;INTS3;MED28;MED1;RNF168;BTBD18;CDC73;NELFE;INTS7;ZMYND11;MED23;MED7;MED19;SRCAP;EAPP;HNRNPU;MED6;MED11;TCERG1;MED29;RNF8;MED26;PARP1;NCBP2;SUPT6H;INTS1;MED9;ELL2;MED27;MED14;ZMYND8;ELL;CDK12;INTS6;MED17;INTS5
prerank                       Positive Regulation Of DNA-templated Transcription, Elongation (GO:0032786)  0.539892  2.096123   0.000000   0.007181       0.043   36/56 31.82%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           MED16;THOC1;MED20;PWWP2B;MED30;MED28;MED1;DDX39B;BTBD18;CDC73;MED23;MED7;SUPT16H;MED19;EAPP;MED6;MED11;TCERG1;MED29;ERCC6;MED26;PARP1;NCBP2;SUPT6H;MED9;ELL2;MED27;MED14;ZMYND8;ELL;CDK12;MED17;MED4;HMGN1;MED31;CDK13
prerank                                                                      mRNA Processing (GO:0006397)  0.439692  2.054994   0.000000   0.007589       0.080 108/211 32.47%                                                                                                                                                                                                                                                                                                                                                                                              RBMX2;USP49;PRPF18;KIN;HNRNPH3;SNRNP70;IK;RBM41;HTATSF1;PPWD1;DDX39B;DHX16;GPKOW;PNN;HNRNPA1;BUD13;SFPQ;PABPC1;RSRC1;SNRNP35;DDX46;NCBP2L;CDC5L;DBR1;PRKACA;CWC27;LSM6;RPRD2;PPIE;CMTR1;SNRPB2;WBP4;SNRNP27;FRA10AC1;SRSF8;LSM2;PPIH;GEMIN7;SRSF1;CPSF6;DDX41;HNRNPU;CTNNBL1;SON;AQR;PAPOLA;SF3B1;GEMIN5;MBLAC1;PRPF31;WDR83;SNRPE;ESS2;TCERG1;U2AF1;SRSF4;ZMAT2;CRNKL1;RBMXL2;MTREX;PLRG1;DHX38;TXNL4A;SNRPD3;HNRNPC;SNRPG;DHX15;NCBP2;PRPF40B;RBM4;SYF2;HNRNPK;SRSF3;LSM3;LSM7;TRA2A;RBM8A;SF3B2;FRG1;SART1;HNRNPA0;RNPC3;SF3B3;CWC22;SNRPF;GPATCH1;SRSF9;PRPF19;HNRNPH1;RBM4B;DHX35;HNRNPR;PRPF3;PPIL1;SRSF12;RBM10;PRPF40A;RPRD1A;SF3A3;MFAP1;RPRD1B;SRRM2;HSPA8;SNRPB;SNIP1;GEMIN6;ISY1;SNRPD1
prerank RNA Splicing, Via Transesterification Reactions With Bulged Adenosine As Nucleophile (GO:0000377)  0.461337  2.118343   0.000000   0.007630       0.031  94/178 32.47%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RBMX2;USP49;HNRNPH3;SNRNP70;IK;RBM41;HTATSF1;PPWD1;DDX39B;DHX16;GPKOW;PNN;HNRNPA1;BUD13;PABPC1;RSRC1;SNRNP35;DDX46;NCBP2L;CDC5L;DBR1;CWC27;LSM6;PPIE;SNRPB2;WBP4;SNRNP27;FRA10AC1;SRSF8;LSM2;PPIH;GEMIN7;SRSF1;DDX41;HNRNPU;CTNNBL1;AQR;SF3B1;GEMIN5;PRPF31;WDR83;SNRPE;ESS2;U2AF1;SRSF4;ZMAT2;CRNKL1;RBMXL2;MTREX;PLRG1;DHX38;TXNL4A;SNRPD3;HNRNPC;SNRPG;DHX15;NCBP2;PRPF40B;RBM4;SYF2;HNRNPK;SRSF3;LSM3;LSM7;TRA2A;RBM8A;SF3B2;FRG1;SART1;RNPC3;SF3B3;CWC22;SNRPF;GPATCH1;SRSF9;PRPF19;HNRNPH1;RBM4B;DHX35;HNRNPR;PRPF3;PPIL1;SRSF12;RBM10;PRPF40A;SF3A3;MFAP1;SRRM2;HSPA8;SNRPB;SNIP1;GEMIN6;ISY1;SNRPD1
prerank                 Positive Regulation Of Transcription Elongation By RNA Polymerase II (GO:0032968)  0.562651  2.055879   0.000000   0.008348       0.080   30/43 31.82%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MED16;MED20;PWWP2B;MED30;MED28;MED1;BTBD18;CDC73;MED23;MED7;MED19;EAPP;MED6;MED11;TCERG1;MED29;MED26;NCBP2;SUPT6H;MED9;ELL2;MED27;MED14;ZMYND8;ELL;CDK12;MED17;MED4;MED31;CDK13
prerank                                                                      Response To BMP (GO:0071772)  0.630048  2.033397   0.000000   0.009183       0.117   13/23 18.99%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   BMP2;BMP4;SMAD9;ADAMTS12;BMPR1A;SFRP1;HJV;TMEM100;GDF2;SMAD4;BMPR1B;BMPR2;BMP6
prerank                Cell Surface Receptor Signaling Pathway Involved In Heart Development (GO:0061311)  0.716950  2.033896   0.001692   0.009948       0.117    6/16  3.90%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   BMP2;BMP4;HEY1;RBPJ;BMPR1A;NOG
prerank                                                  Regulation Of DNA Metabolic Process (GO:0051052)  0.450942  2.003141   0.000000   0.013720       0.178  49/124 23.98%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              THOC1;ENY2;TADA2B;SUPT3H;TAF5L;XRCC5;ING5;YY1;SUPT7L;PPP2CA;JADE1;ING4;DEPDC1B;MYC;MPHOSPH8;NSMCE4A;ZBTB38;NSMCE3;SMC6;CCDC88A;TERF2IP;KAT2A;SMC3;ANKRD17;BAZ1A;UIMC1;TAF5;SIRT7;TAF4;JADE3;CHRAC1;NSMCE2;TMEM98;USP37;FBXO5;SUPT20H;USP1;TAF7;INO80B;BAZ2A;INO80D;ESCO2;ORC3;BABAM1;ACTR5;USP22;RADX;UBE2V2;ACTL6A
prerank                               Transcription Initiation At RNA Polymerase II Promoter (GO:0006367)  0.496608  1.984701   0.000000   0.017473       0.236   28/69 18.64%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 MED16;ERCC3;TAF3;MED20;TAF11;GTF2H2;MED30;POLR2D;MED28;MED1;TAF5;ELOA;POLR2G;MED23;TAF4;TAF4B;MED7;MED19;TAF8;MED6;MED11;TAF1;TAF7;MED29;MAZ;GTF2A2;GTF2E1;MED26

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/GSE149009/GSE149009_clean_clinical_metadata.csv'
df = pd.read_csv(path)

print(df.columns.tolist())
print(df.head(3).to_string())

['patient_id', 'gsm_as_listed_in_dictionary', 'disease_state', 'age', 'gender', 'idh_mutation', 'survival_days', 'tissue', 'gsm', 'gsm_mapping_note', 'expr_column', 'survival_missing']
  patient_id gsm_as_listed_in_dictionary disease_state   age gender idh_mutation  survival_days            tissue         gsm                                                                  gsm_mapping_note expr_column  survival_missing
0         G1                  GSM4487293      GBM (IV)  53.0      M           WT           22.0  GBM tumor tissue  GSM4487293  GEO Series roster sequence; OtB mapping cross-checked against GEO sample records     OtB6179             False
1         G2                  GSM4487294      GBM (IV)  69.0      M          NaN           25.0  GBM tumor tissue  GSM4487294  GEO Series roster sequence; OtB mapping cross-checked against GEO sample records     OtB6180             False
2         G3                  GSM4487295      GBM (IV)  36.0      M           WT           31.0  GBM tumor tissue  GSM4487295  GEO Series roster sequence; OtB mapping cross-checked against GEO sample records     OtB6181             False

In [ ]:
import os

folder = "/content/drive/MyDrive/GSE149009"

for root, dirs, files in os.walk(folder):
    # Avoid listing every file in nested output folders
    depth = root.replace(folder, "").count(os.sep)
    if depth <= 2:
        for file in files:
            print(os.path.join(root, file))

/content/drive/MyDrive/GSE149009/GSE149009_gbm_rna_deseq2.txt
/content/drive/MyDrive/GSE149009/GSE149009_clean_clinical_metadata.csv
/content/drive/MyDrive/GSE149009/results/pca_coordinates.csv
/content/drive/MyDrive/GSE149009/results/expression_qc_summary.csv
/content/drive/MyDrive/GSE149009/results/survival/ranked_by_absolute_correlation.csv
/content/drive/MyDrive/GSE149009/results/survival/gene_survival_associations.csv
/content/drive/MyDrive/GSE149009/results/survival/week2_summary.csv
/content/drive/MyDrive/GSE149009/results/survival/annotated_gene_survival_associations.csv
/content/drive/MyDrive/GSE149009/results/survival/ranked_gene_symbols.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/00_audit_summary.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/01_full_gene_survival_associations.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/02_prerank_all_Ensembl_IDs.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/03_annotated_gene_survival_associations.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/04_prerank_unique_symbols.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/05_GO_Biological_Process_prerank_REBUILT.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/06_significant_GO_pathways_FDR05.csv
/content/drive/MyDrive/GSE149009/recovered_full_analysis/07_final_run_summary.csv

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/GSE149009"

files_to_check = {
    "Audit summary": f"{base}/recovered_full_analysis/00_audit_summary.csv",
    "Final run summary": f"{base}/recovered_full_analysis/07_final_run_summary.csv",
    "Original survival summary": f"{base}/results/survival/week2_summary.csv",
    "Gene associations": f"{base}/recovered_full_analysis/01_full_gene_survival_associations.csv",
}

for name, path in files_to_check.items():
    print(f"\n{'='*65}\n{name}\n{'='*65}")
    if os.path.exists(path):
        df = pd.read_csv(path)
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        if len(df) <= 30:
            print(df.to_string(index=False))
        else:
            print(df.head(3).to_string(index=False))
    else:
        print("File not found:", path)

=================================================================
Audit summary
=================================================================
Shape: (1, 7)
Columns: ['dataset', 'clinical_records', 'expression_genes', 'expression_samples', 'samples_with_survival', 'mean_survival_days', 'median_survival_days']
  dataset  clinical_records  expression_genes  expression_samples  samples_with_survival  mean_survival_days  median_survival_days
GSE149009                68             37361                  68                     59          875.491525                 171.0

=================================================================
Final run summary
=================================================================
Shape: (1, 14)
Columns: ['dataset', 'survival_samples', 'original_expression_genes', 'genes_tested', 'constant_genes_removed', 'invalid_correlations_skipped', 'genes_FDR_below_005', 'IDs_with_symbols', 'unique_symbols_ranked', 'GO_pathways_tested', 'GO_pathways_FDR_below_005', 'gene_sets', 'permutations', 'seed']
  dataset  survival_samples  original_expression_genes  genes_tested  constant_genes_removed  invalid_correlations_skipped  genes_FDR_below_005  IDs_with_symbols  unique_symbols_ranked  GO_pathways_tested  GO_pathways_FDR_below_005                  gene_sets  permutations  seed
GSE149009                59                      37361         30617                    6744                             0                    0             27928                  26709                2710                         66 GO_Biological_Process_2023          1000    42

=================================================================
Original survival summary
=================================================================
Shape: (1, 8)
Columns: ['total_genes_tested', 'constant_genes_removed', 'samples_with_survival', 'significant_genes_FDR_0.05', 'mean_spearman_rho', 'median_spearman_rho', 'positive_correlations', 'negative_correlations']
 total_genes_tested  constant_genes_removed  samples_with_survival  significant_genes_FDR_0.05  mean_spearman_rho  median_spearman_rho  positive_correlations  negative_correlations
              30617                    6744                     59                           0           0.016361             0.022556                  17623                  12944

=================================================================
Gene associations
=================================================================
Shape: (30617, 4)
Columns: ['gene', 'spearman_rho', 'p_value', 'FDR']
           gene  spearman_rho  p_value     FDR
ENSG00000213185      0.480300 0.000118 0.99955
ENSG00000178395      0.472273 0.000159 0.99955
ENSG00000224830      0.459870 0.000248 0.99955

In [ ]:

!pip -q install GEOparse

import GEOparse

gse = GEOparse.get_GEO(
    geo="GSE149009",
    destdir="/content",
    silent=True
)

keywords = ["survival", "status", "death", "follow", "alive",
            "vital", "event", "censor", "days"]

for gsm_id, sample in gse.gsms.items():
    metadata = sample.metadata

    relevant = {}
    for key, values in metadata.items():
        combined = " ".join(map(str, values))
        if any(word in (key + " " + combined).lower()
               for word in keywords):
            relevant[key] = values

    if relevant:
        print(f"\n{gsm_id} | {metadata.get('title', [''])[0]}")
        for key, values in relevant.items():
            print(f"  {key}: {values}")

GSM4487293 | G1
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 53', 'gender: M', 'idh_mutation: WT', 'survival (days): 22', 'tissue: GBM tumor tissue']

GSM4487294 | G2
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 69', 'gender: M', 'idh_mutation: NA', 'survival (days): 25', 'tissue: GBM tumor tissue']

GSM4487295 | G3
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 36', 'gender: M', 'idh_mutation: WT', 'survival (days): 31', 'tissue: GBM tumor tissue']

GSM4487296 | G4
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 68', 'gender: M', 'idh_mutation: NA', 'survival (days): 32', 'tissue: GBM tumor tissue']

GSM4487297 | G5
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 74', 'gender: F', 'idh_mutation: NA', 'survival (days): 185', 'tissue: GBM tumor tissue']

GSM4487298 | G6
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 69', 'gender: F', 'idh_mutation: NA', 'survival (days): 43', 'tissue: GBM tumor tissue']

GSM4487299 | G7
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 65', 'gender: M', 'idh_mutation: WT', 'survival (days): 48', 'tissue: GBM tumor tissue']

GSM4487300 | G8
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 66', 'gender: M', 'idh_mutation: WT', 'survival (days): 77', 'tissue: GBM tumor tissue']

GSM4487301 | G9
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 47', 'gender: F', 'idh_mutation: WT', 'survival (days): 71', 'tissue: GBM tumor tissue']

GSM4487302 | G10
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 66', 'gender: M', 'idh_mutation: MUT', 'survival (days): 147', 'tissue: GBM tumor tissue']

GSM4487303 | G11
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 23', 'gender: F', 'idh_mutation: WT', 'survival (days): 88', 'tissue: GBM tumor tissue']

GSM4487304 | G12
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 19', 'gender: F', 'idh_mutation: WT', 'survival (days): 93', 'tissue: GBM tumor tissue']

GSM4487305 | G13
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 37', 'gender: M', 'idh_mutation: WT', 'survival (days): 93', 'tissue: GBM tumor tissue']

GSM4487306 | G14
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 66', 'gender: M', 'idh_mutation: WT', 'survival (days): 104', 'tissue: GBM tumor tissue']

GSM4487307 | G15
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 49', 'gender: M', 'idh_mutation: WT', 'survival (days): 107', 'tissue: GBM tumor tissue']

GSM4487308 | G16
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 59', 'gender: M', 'idh_mutation: NA', 'survival (days): 114', 'tissue: GBM tumor tissue']

GSM4487309 | G17
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 59', 'gender: M', 'idh_mutation: WT', 'survival (days): 115', 'tissue: GBM tumor tissue']

GSM4487310 | G18
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 66', 'gender: M', 'idh_mutation: WT', 'survival (days): 151', 'tissue: GBM tumor tissue']

GSM4487311 | G19
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 50', 'gender: F', 'idh_mutation: WT', 'survival (days): 126', 'tissue: GBM tumor tissue']

GSM4487312 | G20
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 58', 'gender: F', 'idh_mutation: WT', 'survival (days): 131', 'tissue: GBM tumor tissue']

GSM4487313 | G21
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 64', 'gender: M', 'idh_mutation: WT', 'survival (days): 161', 'tissue: GBM tumor tissue']

GSM4487314 | G22
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 63', 'gender: M', 'idh_mutation: WT', 'survival (days): 164', 'tissue: GBM tumor tissue']

GSM4487315 | G23
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 73', 'gender: F', 'idh_mutation: WT', 'survival (days): 128', 'tissue: GBM tumor tissue']

GSM4487316 | G24
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 54', 'gender: M', 'idh_mutation: NA', 'survival (days): 171', 'tissue: GBM tumor tissue']

GSM4487317 | G25
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 57', 'gender: F', 'idh_mutation: WT', 'survival (days): 177', 'tissue: GBM tumor tissue']

GSM4487318 | G26
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 64', 'gender: M', 'idh_mutation: NA', 'survival (days): 181', 'tissue: GBM tumor tissue']

GSM4487319 | G27
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 62', 'gender: M', 'idh_mutation: WT', 'survival (days): 182', 'tissue: GBM tumor tissue']

GSM4487320 | G28
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 34', 'gender: M', 'idh_mutation: NA', 'survival (days): 183', 'tissue: GBM tumor tissue']

GSM4487321 | G29
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 79', 'gender: M', 'idh_mutation: NA', 'survival (days): 126', 'tissue: GBM tumor tissue']

GSM4487322 | G30
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 68', 'gender: M', 'idh_mutation: WT', 'survival (days): 76', 'tissue: GBM tumor tissue']

GSM4487323 | G31
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 72', 'gender: M', 'idh_mutation: NA', 'survival (days): 120', 'tissue: GBM tumor tissue']

GSM4487324 | G32
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 78', 'gender: F', 'idh_mutation: WT', 'survival (days): 87', 'tissue: GBM tumor tissue']

GSM4487325 | G33
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 70', 'gender: F', 'idh_mutation: WT', 'survival (days): 91', 'tissue: GBM tumor tissue']

GSM4487326 | G34
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 71', 'gender: F', 'idh_mutation: WT', 'survival (days): 136', 'tissue: GBM tumor tissue']

GSM4487327 | G35
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 73', 'gender: M', 'idh_mutation: NA', 'survival (days): 116', 'tissue: GBM tumor tissue']

GSM4487328 | G36
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487329 | G37
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: F', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487330 | G38
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487331 | G39
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487332 | G40
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487333 | G41
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487334 | G42
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 43', 'gender: M', 'idh_mutation: NA', 'survival (days): 3896', 'tissue: GBM tumor tissue']

GSM4487335 | G43
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 37', 'gender: M', 'idh_mutation: NA', 'survival (days): 3762', 'tissue: GBM tumor tissue']

GSM4487336 | G44
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 44', 'gender: M', 'idh_mutation: NA', 'survival (days): 2739', 'tissue: GBM tumor tissue']

GSM4487337 | G45
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 34', 'gender: M', 'idh_mutation: NA', 'survival (days): 3647', 'tissue: GBM tumor tissue']

GSM4487338 | G46
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 70', 'gender: F', 'idh_mutation: NA', 'survival (days): 2338', 'tissue: GBM tumor tissue']

GSM4487339 | G47
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 68', 'gender: F', 'idh_mutation: NA', 'survival (days): 2275', 'tissue: GBM tumor tissue']

GSM4487340 | G48
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 69', 'gender: F', 'idh_mutation: NA', 'survival (days): 2249', 'tissue: GBM tumor tissue']

GSM4487341 | G49
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: F', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487342 | G50
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 51', 'gender: M', 'idh_mutation: NA', 'survival (days): 2090', 'tissue: GBM tumor tissue']

GSM4487343 | G51
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: M', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

GSM4487344 | G52
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 42', 'gender: M', 'idh_mutation: WT', 'survival (days): 2180', 'tissue: GBM tumor tissue']

GSM4487345 | G53
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 40', 'gender: F', 'idh_mutation: MUT', 'survival (days): 2044', 'tissue: GBM tumor tissue']

GSM4487346 | G54
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 25', 'gender: M', 'idh_mutation: NA', 'survival (days): 1574', 'tissue: GBM tumor tissue']

GSM4487347 | G55
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 49', 'gender: M', 'idh_mutation: NA', 'survival (days): 1537', 'tissue: GBM tumor tissue']

GSM4487348 | G56
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 72', 'gender: F', 'idh_mutation: MUT', 'survival (days): 1343', 'tissue: GBM tumor tissue']

GSM4487349 | G57
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 59', 'gender: F', 'idh_mutation: NA', 'survival (days): 1342', 'tissue: GBM tumor tissue']

GSM4487350 | G58
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 70', 'gender: M', 'idh_mutation: NA', 'survival (days): 1331', 'tissue: GBM tumor tissue']

GSM4487351 | G59
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 63', 'gender: M', 'idh_mutation: NA', 'survival (days): 1438', 'tissue: GBM tumor tissue']

GSM4487352 | G60
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 61', 'gender: M', 'idh_mutation: NA', 'survival (days): 1292', 'tissue: GBM tumor tissue']

GSM4487353 | G61
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 42', 'gender: M', 'idh_mutation: NA', 'survival (days): 2593', 'tissue: GBM tumor tissue']

GSM4487354 | G62
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 60', 'gender: M', 'idh_mutation: WT', 'survival (days): 1273', 'tissue: GBM tumor tissue']

GSM4487355 | G63
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 62', 'gender: F', 'idh_mutation: NA', 'survival (days): 1256', 'tissue: GBM tumor tissue']

GSM4487356 | G64
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 77', 'gender: M', 'idh_mutation: NA', 'survival (days): 1233', 'tissue: GBM tumor tissue']

GSM4487357 | G65
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 56', 'gender: F', 'idh_mutation: NA', 'survival (days): 1156', 'tissue: GBM tumor tissue']

GSM4487358 | G66
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 59', 'gender: M', 'idh_mutation: WT', 'survival (days): 1150', 'tissue: GBM tumor tissue']

GSM4487359 | G67
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: 67', 'gender: F', 'idh_mutation: WT', 'survival (days): 2014', 'tissue: GBM tumor tissue']

GSM4487360 | G68
  status: ['Public on Mar 02 2021']
  characteristics_ch1: ['disease state: GBM (IV)', 'age: NA', 'gender: F', 'idh_mutation: NA', 'survival (days): NA', 'tissue: GBM tumor tissue']

In [ ]:

import pandas as pd
import os

path = (
    "/content/drive/MyDrive/GSE149009/"
    "recovered_full_analysis/"
    "05_GO_Biological_Process_prerank_REBUILT.csv"
)

gsea = pd.read_csv(path)

print("Columns:", gsea.columns.tolist())
print("Total pathways:", len(gsea))

# Identify the relevant columns despite possible naming differences
fdr_col = next(
    (c for c in gsea.columns if c.lower() in ["fdr q-val", "fdr", "fdr_q_val"]),
    None
)
nes_col = next(
    (c for c in gsea.columns if c.lower() in ["nes", "normalized_enrichment_score"]),
    None
)

if fdr_col and nes_col:
    gsea[fdr_col] = pd.to_numeric(gsea[fdr_col], errors="coerce")
    gsea[nes_col] = pd.to_numeric(gsea[nes_col], errors="coerce")

    sig = gsea[gsea[fdr_col] < 0.05].copy()

    print("\nSignificant pathways (FDR < 0.05):", len(sig))
    print("Positive NES:", (sig[nes_col] > 0).sum())
    print("Negative NES:", (sig[nes_col] < 0).sum())

    print("\nTop 15 by FDR:")
    print(
        sig.sort_values(fdr_col)[
            [c for c in ["Term", "NES", "NOM p-val", "FDR q-val"]
             if c in sig.columns]
        ].head(15).to_string(index=False)
    )
else:
    print("Could not automatically identify FDR/NES columns.")
    print(gsea.head().to_string(index=False))

Columns: ['Name', 'Term', 'ES', 'NES', 'NOM p-val', 'FDR q-val', 'FWER p-val', 'Tag %', 'Gene %', 'Lead_genes']
Total pathways: 2710

Significant pathways (FDR < 0.05): 66
Positive NES: 59
Negative NES: 7

Top 15 by FDR:
                                                                                             Term      NES  NOM p-val  FDR q-val
                                                           Mitochondrial Translation (GO:0032543) 2.349539   0.000000   0.000000
                                                       Mitochondrial Gene Expression (GO:0140053) 2.295154   0.000000   0.000449
                                                                Chromatin Remodeling (GO:0006338) 2.160135   0.000000   0.004787
                                                      mRNA Splicing, Via Spliceosome (GO:0000398) 2.115475   0.000000   0.006283
                                                              Chromatin Organization (GO:0006325) 2.087810   0.000000   0.006540
                                          Monoubiquitinated Protein Deubiquitination (GO:0035520) 2.071687   0.000000   0.006682
                      Positive Regulation Of DNA-templated Transcription, Elongation (GO:0032786) 2.096123   0.000000   0.007181
                         Regulation Of Transcription Elongation By RNA Polymerase II (GO:0034243) 2.074812   0.000000   0.007181
                                                                     mRNA Processing (GO:0006397) 2.054994   0.000000   0.007589
RNA Splicing, Via Transesterification Reactions With Bulged Adenosine As Nucleophile (GO:0000377) 2.118343   0.000000   0.007630
                Positive Regulation Of Transcription Elongation By RNA Polymerase II (GO:0032968) 2.055879   0.000000   0.008348
                                                                     Response To BMP (GO:0071772) 2.033397   0.000000   0.009183
               Cell Surface Receptor Signaling Pathway Involved In Heart Development (GO:0061311) 2.033896   0.001692   0.009948
                                                 Regulation Of DNA Metabolic Process (GO:0051052) 2.003141   0.000000   0.013720
                              Transcription Initiation At RNA Polymerase II Promoter (GO:0006367) 1.984701   0.000000   0.017473